# Generated by Django 5.2.10 on 2026-02-17 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_title', models.CharField(default='Est. 2012 • Fine Dining', max_length=100)),
                ('main_title_white', models.CharField(default='Crafting', max_length=100)),
                ('main_title_span', models.CharField(default='Moments', max_length=50)),
                ('main_title_bottom', models.CharField(default='Beyond Taste', max_length=100)),
                ('menu_button_text', models.CharField(default='View Our Menu', max_length=50)),
                ('story_button_text', models.CharField(default='Our Story', max_length=50)),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='banner/')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': '1. Hero Section',
            },
        ),
        migrations.CreateModel(
            name='RestaurantFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_class', models.CharField(help_text='e.g., fas fa-leaf', max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': '2. Restaurant Features',
                'ordering': ['order'],
            },
        ),
    ]
