# Generated by Django 5.2.10 on 2026-02-17 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='about/')),
                ('experience_years', models.CharField(default='12Y', max_length=10)),
                ('legacy_tag', models.CharField(default='The Legacy', max_length=50)),
                ('title', models.CharField(default='Every Flavor Tells A Royal Story', max_length=200)),
                ('description', models.TextField()),
                ('stat1_count', models.CharField(default='50+', max_length=20)),
                ('stat1_label', models.CharField(default='Master Recipes', max_length=50)),
                ('stat2_count', models.CharField(default='20+', max_length=20)),
                ('stat2_label', models.CharField(default='Expert Chefs', max_length=50)),
                ('stat3_count', models.CharField(default='100%', max_length=20)),
                ('stat3_label', models.CharField(default='Satisfaction', max_length=50)),
            ],
            options={
                'verbose_name_plural': '3. About Section',
            },
        ),
    ]
