# Generated by Django 5.2.10 on 2026-02-18 15:35

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_aboutsection_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herosection',
            name='background_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='background_image'),
        ),
    ]
