# Generated by Django 5.2.10 on 2026-02-17 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_herosection'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HeroSection',
        ),
    ]
