# Generated by Django 5.2.10 on 2026-02-18 15:25

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_delete_herosection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutstory',
            name='main_image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='main_image'),
        ),
        migrations.AlterField(
            model_name='chef',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='main_image'),
        ),
    ]
