# Generated by Django 5.2.10 on 2026-02-18 15:26

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_aboutstory_main_image_alter_chef_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chef',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
