# Generated by Django 5.2.10 on 2026-02-12 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
