# Generated by Django 5.2.10 on 2026-02-14 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_remove_offer_image_offer_food_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComboDeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('discount_percentage', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('foods', models.ManyToManyField(related_name='combo_deals', to='menu.food')),
            ],
        ),
    ]
