# Generated by Django 5.2.10 on 2026-02-15 13:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_testimonial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='combodeal',
            name='discount_percentage',
        ),
        migrations.RemoveField(
            model_name='combodeal',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='combodeal',
            name='foods',
        ),
        migrations.RemoveField(
            model_name='combodeal',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='combodeal',
            name='title',
        ),
        migrations.AddField(
            model_name='combodeal',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='combodeal',
            name='discount_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='combodeal',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='combos/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='combodeal',
            name='name',
            field=models.CharField(default='combo', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='combodeal',
            name='original_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='combodeal',
            name='description',
            field=models.TextField(default='Special Combo', help_text='যেমন: ২টা বার্গার + ১টা কোক'),
            preserve_default=False,
        ),
    ]
