# Generated by Django 5.2.10 on 2026-02-15 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0008_remove_combodeal_discount_percentage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='combodeal',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='combodeal',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
