# Generated by Django 5.2.10 on 2026-02-16 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0010_testimonial_user_alter_testimonial_designation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlashDeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='The "Gemini" Mega Combo', max_length=200)),
                ('description', models.TextField()),
                ('discount_text', models.CharField(default='40% OFF', max_length=50)),
                ('image', models.ImageField(upload_to='deals/')),
                ('end_time', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
