# Generated by Django 5.2.10 on 2026-02-19 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0015_food_is_surprise_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='mood_tag',
            field=models.CharField(choices=[('happy', 'Happy (Celebration)'), ('stressed', 'Stressed (Comfort Food)'), ('romantic', 'Romantic (Date Night)'), ('lazy', 'Lazy (Quick Bites)')], default='happy', max_length=20),
        ),
    ]
