# Generated by Django 5.2.10 on 2026-02-12 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_food_stock'),
        ('orders', '0002_alter_orderitem_food_name_alter_orderitem_order_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='food_name',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='food',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='menu.food'),
            preserve_default=False,
        ),
    ]
