# Generated by Django 5.2.10 on 2026-02-15 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0009_alter_combodeal_description_alter_combodeal_name'),
        ('orders', '0003_remove_orderitem_food_name_orderitem_food'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='combo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='menu.combodeal'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='food',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='menu.food'),
        ),
    ]
